{% set name = "ModestImage" %}
{% set version = "0.2" %}
{% set sha256 = "4b71af469f0c4ba73a915c6a96040cc54e81c9ce0c793e6d3e6bb72a99cb53dc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - mpl31.patch
    - np124.patch
    - mpl37.patch

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - modest_image

about:
  home: https://pypi.org/project/ModestImage
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Friendlier matplotlib interaction with large images

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
